### ISSUE TITLE
py27 test fails

### ISSUE THREAD

**Issue by ThomasWaldmann** [discorporate/flatland#17]
tw@tux:~/w/flatland$ tox -e py27
GLOB sdist-make: /home/tw/w/flatland/setup.py
py27 inst-nodeps: /home/tw/w/flatland/.tox/.tmp/package/1/flatland-0.8.zip
py27 installed: alabaster==0.7.12,Babel==2.6.0,blinker==1.4,certifi==2018.10.15,chardet==3.0.4,docutils==0.14,flatland==0.8,Genshi==0.7.1,idna==2.7,imagesize==1.1.0,Jinja2==2.10,MarkupSafe==1.0,nose==1.3.7,packaging==18.0,Pygments==2.2.0,pyparsing==2.2.2,pytz==2018.7,requests==2.20.0,six==1.11.0,snowballstemmer==1.2.1,Sphinx==1.8.1,sphinxcontrib-websupport==1.1.0,typing==3.6.6,urllib3==1.24
py27 run-test-pre: PYTHONHASHSEED='265513504'

py27 runtests: commands[0] | nosetests
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 723 tests in 0.443s

OK

py27 runtests: commands[1] | sphinx-build -b doctest docs/source docs/build
Running Sphinx v1.8.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 27 source files that are out of date
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] validation/builtin

WARNING: autodoc: failed to import class u'string.NANPphone' from module u'flatland.validation'; the following exception was raised:
No module named string
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
running tests...

Document: schema/dicts
----------------------
1 items passed all tests:
  10 tests in default
10 tests in 1 items.
10 passed and 0 failed.
Test passed.

Document: validation/builtin
----------------------------
**********************************************************************
File "validation/builtin.rst", line ?, in default
Failed example:
    import flatland
    from flatland.validation import NotDuplicated

    validator = NotDuplicated(failure="Please enter each color only once.")
    schema = List.of(String.named('favorite_color')).\
                  using(validators=[validator])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 5, in <module>
        schema = List.of(String.named('favorite_color')).\
    NameError: name 'List' is not defined
**********************************************************************
File "validation/builtin.rst", line ?, in default
Failed example:
    from flatland import Dict, Integer
    from flatland.validation import SetWithKnownFields

    schema = Dict.of(Integer.named('x'), Integer.named('y')).\
                  validated_by(SetWithKnownFields())
    element = schema()

    element.set({'x': 123})
    assert element.validate()

    element.set({'x': 123, 'z': 789})
    assert not element.validate()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 9, in <module>
        assert element.validate()
    AssertionError
**********************************************************************
File "validation/builtin.rst", line ?, in default
Failed example:
    from flatland import Dict, Integer
    from flatland.validation import SetWithAllFields

    schema = Dict.of(Integer.named('x'), Integer.named('y')).\
                  validated_by(SetWithAllFields())
    element = schema()

    element.set({'x': 123, 'y': 456})
    assert element.validate()

    element.set({'x': 123})
    assert not element.validate()

    element.set({'x': 123, 'y': 456, 'z': 789})
    assert not element.validate()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 14, in <module>
        element.set({'x': 123, 'y': 456, 'z': 789})
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/flatland/schema/containers.py", line 1007, in set
        list(mismatch)))
    KeyError: "Subset Dict None schema does not allow keys [u'z']"
**********************************************************************
1 items had failures:
   3 of  20 in default
20 tests in 1 items.
17 passed and 3 failed.
***Test Failed*** 3 failures.

Document: schema/traversal
--------------------------
1 items passed all tests:
  29 tests in default
29 tests in 1 items.
29 passed and 0 failed.
Test passed.

Document: schema/enums
----------------------
1 items passed all tests:
   8 tests in default
8 tests in 1 items.
8 passed and 0 failed.
Test passed.

Document: schema/declarative
----------------------------
1 items passed all tests:
   9 tests in default
9 tests in 1 items.
9 passed and 0 failed.
Test passed.

Document: schema/properties
---------------------------
2 items passed all tests:
   7 tests in props
   4 tests in pyann
11 tests in 2 items.
11 passed and 0 failed.
Test passed.

Document: patterns/widgets
--------------------------
**********************************************************************
File "patterns/widgets.rst", line 105, in genshi
Failed example:
    from genshi.template import TemplateLoader
    from flatland.out.genshi import setup
    loader = TemplateLoader(['docs/_fixtures/genshi'], callback=setup)
    template = loader.load('form.html')
    print template.generate(form=form).render()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest genshi[0]>", line 4, in <module>
        template = loader.load('form.html')
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/genshi/template/loader.py", line 246, in load
        raise TemplateNotFound(filename, search_path)
    TemplateNotFound: Template "form.html" not found
**********************************************************************
File "patterns/widgets.rst", line 209, in jinja
Failed example:
    from jinja2 import Environment, FileSystemLoader
    from flatland.out.markup import Generator
    loader = FileSystemLoader('docs/_fixtures/jinja')
    env = Environment(loader=loader, extensions=['jinja2.ext.do'])
    env.globals['form_generator'] = Generator('html')
    template = env.get_template('form.html')
    print template.render(form=form)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest jinja[0]>", line 6, in <module>
        template = env.get_template('form.html')
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/home/tw/w/flatland/.tox/py27/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    TemplateNotFound: form.html
**********************************************************************
2 items had failures:
   1 of   1 in genshi
   1 of   1 in jinja
2 tests in 2 items.
0 passed and 2 failed.
***Test Failed*** 2 failures.

Document: markup
----------------
3 items passed all tests:
   9 tests in generatorintro
   6 tests in transforms1
  26 tests in transforms2
41 tests in 3 items.
41 passed and 0 failed.
Test passed.

Document: validation/basic
--------------------------
2 items passed all tests:
  18 tests in default
   5 tests in signals
23 tests in 2 items.
23 passed and 0 failed.
Test passed.

Document: schema/lists
----------------------
1 items passed all tests:
  17 tests in default
17 tests in 1 items.
17 passed and 0 failed.
Test passed.

Document: validation/api
------------------------
2 items passed all tests:
   3 tests in NoShouting
   3 tests in default
6 tests in 2 items.
6 passed and 0 failed.
Test passed.

Document: intro
---------------
1 items passed all tests:
   7 tests in default
7 tests in 1 items.
7 passed and 0 failed.
Test passed.

Document: validation/custom
---------------------------
1 items passed all tests:
  17 tests in default
17 tests in 1 items.
17 passed and 0 failed.
Test passed.

Document: api
-------------
1 items passed all tests:
  24 tests in default
24 tests in 1 items.
24 passed and 0 failed.
Test passed.

Document: schema/schema
-----------------------
3 items passed all tests:
  27 tests in default
   3 tests in find
   7 tests in fso
37 tests in 3 items.
37 passed and 0 failed.
Test passed.

Document: schema/compound
-------------------------
**********************************************************************
File "schema/compound.rst", line ?, in default
Failed example:
    el2[1].value
Expected:
    u'bar'
Got:
    u'o'
**********************************************************************
File "schema/compound.rst", line ?, in default
Failed example:
    el2.value
Expected:
    u'foo,bar'
Got:
    u'f,o,o,,,b,a,r'
**********************************************************************
File "schema/compound.rst", line ?, in default
Failed example:
    schema('a  ,  b,c,d').value
Expected:
    u'a, b, c, d'
Got:
    u'a, , , ,, , , b, ,, c, ,, d'
**********************************************************************
1 items had failures:
   3 of  14 in default
14 tests in 1 items.
11 passed and 3 failed.
***Test Failed*** 3 failures.

Doctest summary
===============
  275 tests
    8 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build finished with problems, 1 warning.
```

**Comment by ThomasWaldmann** [comment]
See #22.
