### ISSUE TITLE
py37 StopIteration issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [discorporate/flatland#52]
```
  File ".tox/py37/lib/python3.7/site-packages/flatland/schema/base.py", line 355, in path
    return itertools.chain(reversed(list(self.parents)), (self,))
RuntimeError: generator raised StopIteration
```

Since 3.7 this is a RuntimeError, before it was just a deprecation warning.

**Comment by ThomasWaldmann** [comment]
Maybe related:
```
Traceback (most recent call last):
  File ".tox/py37/lib/python3.7/site-packages/flatland/schema/base.py", line 350, in parents
    raise StopIteration()
StopIteration
```

**Comment by ThomasWaldmann** [comment]
Already fixed by recent py3 work and merged into master.

Guess I only need a new release...
